//
//  CryptoDetailInteractor.swift
//  crypto_info
//
//  Created Phattarapon Jungtakarn on 18/8/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CryptoDetailInteractor {

    weak var presenter: CryptoDetailPresenterProtocol?
}

extension CryptoDetailInteractor: CryptoDetailInteractorProtocol {
    
    func fetchYesterdayCryptoData(id: String) {
        let dateYesterdayString = Date.yesterday.dateStringddMMyyyy()
        
        CryptoAPIHelper.sharedInstance().fetchCryptoYesterdayHistoryAPI(id: id, date: dateYesterdayString, localization: "en") { statusFetchCryptoHistoryAPI in
            if statusFetchCryptoHistoryAPI == "ok" {
                if let historyData = UserSession.shared.getCryptoYesterdayHistoryData() {
                    self.fetchToDayCryptoData(yesterdayCryptoData: historyData, id: id)
                }
            } else {
                self.presenter?.notifyDisplayAlert(title: "Error!", message: "Someting Wrong.")
            }
        }
    }
    
    func fetchToDayCryptoData(yesterdayCryptoData: CryptoHistoryEntity, id: String) {
        let dateNowString = Date.yesterday.dateStringddMMyyyy()
        
        CryptoAPIHelper.sharedInstance().fetchCryptoHistoryAPI(id: id, date: dateNowString, localization: "en") { statusFetchCryptoHistoryAPI in
            if statusFetchCryptoHistoryAPI == "ok" {
                if let historyData = UserSession.shared.getCryptoHistoryData() {
                    self.presenter?.notifyDisplayHistoryCryptoData(yesterdayCryptoData: yesterdayCryptoData, toDayCryptoData: historyData)
                }
            } else {
                self.presenter?.notifyDisplayAlert(title: "Error!", message: "Someting Wrong.")
            }
        }
    }
    
}
