//
//  CryptoDetailProtocols.swift
//  crypto_info
//
//  Created Phattarapon Jungtakarn on 18/8/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CryptoDetailWireframeProtocol: class {
    func routeToMain()
}
//MARK: Presenter -
protocol CryptoDetailPresenterProtocol: class {
    func notifyGetCryptoDetail(data: CryptocurrencyEntity)
    func notifyRouteToMain()
    func notifyDisplayHistoryCryptoData(yesterdayCryptoData: CryptoHistoryEntity, toDayCryptoData: CryptoHistoryEntity)
    func checkIsNegative(value: Double) -> Bool
    func notifyDisplayAlert(title: String, message: String)
}

//MARK: Interactor -
protocol CryptoDetailInteractorProtocol: class {
    var presenter: CryptoDetailPresenterProtocol?  { get set }
    func fetchYesterdayCryptoData(id: String)
    func fetchToDayCryptoData(yesterdayCryptoData: CryptoHistoryEntity, id: String)
}

//MARK: View -
protocol CryptoDetailViewProtocol: class {
    var presenter: CryptoDetailPresenterProtocol?  { get set }
    func displayHeaderNameCrypto(name: String)
    func displayHistoryCryptoData(historyData: CryptoHistoryDisplayEntity)
    func displayAlert(title: String, message: String)
}
