//
//  CryptoDetailRouter.swift
//  crypto_info
//
//  Created Phattarapon Jungtakarn on 18/8/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CryptoDetailRouter {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CryptoDetailViewController(nibName: nil, bundle: nil)
        let interactor = CryptoDetailInteractor()
        let router = CryptoDetailRouter()
        let presenter = CryptoDetailPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    static func createModuleWithIDCryptoData(data: CryptocurrencyEntity) -> UIViewController {
        let view = CryptoDetailRouter.createModule() as! CryptoDetailViewController
        
        view.presenter?.notifyGetCryptoDetail(data: data)
        
        return view
    }
}

extension CryptoDetailRouter: CryptoDetailWireframeProtocol {
    
    func routeToMain() {
        self.viewController?.navigationController?.popViewController(animated: true)
    }
    
}
