//
//  CryptoDetailPresenter.swift
//  crypto_info
//
//  Created Phattarapon Jungtakarn on 18/8/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CryptoDetailPresenter {

    weak private var view: CryptoDetailViewProtocol?
    var interactor: CryptoDetailInteractorProtocol?
    private let router: CryptoDetailWireframeProtocol

    init(interface: CryptoDetailViewProtocol, interactor: CryptoDetailInteractorProtocol?, router: CryptoDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension CryptoDetailPresenter: CryptoDetailPresenterProtocol {
    
    func notifyGetCryptoDetail(data: CryptocurrencyEntity) {
        self.interactor?.fetchYesterdayCryptoData(id: data.id)
        self.view?.displayHeaderNameCrypto(name: data.name)
    }
    
    func notifyRouteToMain() {
        self.router.routeToMain()
    }
    
    func notifyDisplayHistoryCryptoData(yesterdayCryptoData: CryptoHistoryEntity, toDayCryptoData: CryptoHistoryEntity) {
        let percentChangePrice = ((toDayCryptoData.current_price - yesterdayCryptoData.current_price) / yesterdayCryptoData.current_price) * 100
        let percentChangeMarketCap = ((toDayCryptoData.market_cap - yesterdayCryptoData.market_cap) / yesterdayCryptoData.market_cap) * 100
        let percentChangeVolume = ((toDayCryptoData.total_volume - yesterdayCryptoData.total_volume) / yesterdayCryptoData.total_volume) * 100
        
        let history = CryptoHistoryDisplayEntity(pervious_price: yesterdayCryptoData.current_price.round(to:2),
                                               price: toDayCryptoData.current_price.round(to:2),
                                               percent_change_price: percentChangePrice.round(to:2),
                                               pervious_market_cap: yesterdayCryptoData.market_cap.round(to:2),
                                               market_cap: toDayCryptoData.market_cap.round(to:2),
                                               percent_market_cap: percentChangeMarketCap.round(to:2),
                                               pervious_volume: yesterdayCryptoData.total_volume.round(to:2),
                                               volume: toDayCryptoData.total_volume.round(to:2),
                                               percent_volume: percentChangeVolume.round(to:2))
        
        self.view?.displayHistoryCryptoData(historyData: history)
    }
    
    func checkIsNegative(value: Double) -> Bool {
        let s = String(value)
        
        if s.hasPrefix("-") {
           return true
        } else {
          return false
        }
    }
    
    func notifyDisplayAlert(title: String, message: String) {
        self.view?.displayAlert(title: title, message: message)
    }
    
}
