//
//  MainProtocols.swift
//  crypto_info
//
//  Created Phattarapon Jungtakarn on 18/8/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MainWireframeProtocol: class {
    func routeToHistoryCrypto(data: CryptocurrencyEntity)
}
//MARK: Presenter -
protocol MainPresenterProtocol: class {
    func notifyViewDidLoad()
    func notifyDisplayCryptoData(cryptoData: [CryptocurrencyEntity])
    func notifyRouteToHistoryCrypto(data: CryptocurrencyEntity)
    func notifyDisplayAlert(title: String, message: String)
}

//MARK: Interactor -
protocol MainInteractorProtocol: class {
    var presenter: MainPresenterProtocol?  { get set }
    func fetchCryptoListsData()
}

//MARK: View -
protocol MainViewProtocol: class {
    var presenter: MainPresenterProtocol?  { get set }
    func displayCryptoData(cryptoData: [CryptocurrencyEntity])
    func displayAlert(title: String, message: String)
}
