//
//  MainInteractor.swift
//  crypto_info
//
//  Created Phattarapon Jungtakarn on 18/8/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainInteractor {

    weak var presenter: MainPresenterProtocol?
}

extension MainInteractor: MainInteractorProtocol {
    
    func fetchCryptoListsData() {
        CryptoAPIHelper.sharedInstance().fetchCryptoListsAPI { statusFetchCryptoListsAPI in
            if statusFetchCryptoListsAPI == "ok" {
                if let cryptoData = UserSession.shared.getCryptoData() {
                    self.presenter?.notifyDisplayCryptoData(cryptoData: cryptoData)
                }
            } else {
                self.presenter?.notifyDisplayAlert(title: "Error!", message: "Someting Wrong.")
            }
        }
    }
    
}
