//
//  MainPresenter.swift
//  crypto_info
//
//  Created Phattarapon Jungtakarn on 18/8/2566 BE.
//  Copyright © 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainPresenter {

    weak private var view: MainViewProtocol?
    var interactor: MainInteractorProtocol?
    private let router: MainWireframeProtocol

    init(interface: MainViewProtocol, interactor: MainInteractorProtocol?, router: MainWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension MainPresenter: MainPresenterProtocol {
    
    func notifyViewDidLoad() {
        self.interactor?.fetchCryptoListsData()
    }
    
    func notifyDisplayCryptoData(cryptoData: [CryptocurrencyEntity]) {
        self.view?.displayCryptoData(cryptoData: cryptoData)
    }
    
    func notifyRouteToHistoryCrypto(data: CryptocurrencyEntity) {
        self.router.routeToHistoryCrypto(data: data)
    }
    
    func notifyDisplayAlert(title: String, message: String) {
        self.view?.displayAlert(title: title, message: message)
    }
    
}
